export const COUNTRY_CODES: { code: string; label: string }[] = [
  { code: '+90', label: 'Türkiye' },
  { code: '+1', label: 'ABD / Kanada' },
  { code: '+44', label: 'Birleşik Krallık' },
  { code: '+49', label: 'Almanya' },
  { code: '+33', label: 'Fransa' },
  { code: '+39', label: 'İtalya' },
  { code: '+34', label: 'İspanya' },
  { code: '+31', label: 'Hollanda' },
  { code: '+32', label: 'Belçika' },
  { code: '+43', label: 'Avusturya' },
  { code: '+41', label: 'İsviçre' },
  { code: '+46', label: 'İsveç' },
  { code: '+47', label: 'Norveç' },
  { code: '+45', label: 'Danimarka' },
  { code: '+358', label: 'Finlandiya' },
  { code: '+48', label: 'Polonya' },
  { code: '+420', label: 'Çekya' },
  { code: '+36', label: 'Macaristan' },
  { code: '+40', label: 'Romanya' },
  { code: '+30', label: 'Yunanistan' },
  { code: '+351', label: 'Portekiz' },
  { code: '+7', label: 'Rusya' },
  { code: '+380', label: 'Ukrayna' },
  { code: '+966', label: 'Suudi Arabistan' },
  { code: '+971', label: 'BAE' },
  { code: '+20', label: 'Mısır' },
  { code: '+27', label: 'Güney Afrika' },
  { code: '+91', label: 'Hindistan' },
  { code: '+86', label: 'Çin' },
  { code: '+81', label: 'Japonya' },
  { code: '+82', label: 'Güney Kore' },
  { code: '+61', label: 'Avustralya' },
  { code: '+55', label: 'Brezilya' },
  { code: '+52', label: 'Meksika' },
  { code: '+54', label: 'Arjantin' },
  { code: '+353', label: 'İrlanda' },
  { code: '+64', label: 'Yeni Zelanda' },
  { code: '+60', label: 'Malezya' },
  { code: '+65', label: 'Singapur' },
  { code: '+62', label: 'Endonezya' },
  { code: '+98', label: 'İran' },
  { code: '+964', label: 'Irak' },
  { code: '+962', label: 'Ürdün' },
  { code: '+972', label: 'İsrail' },
]
