export const COUNTRY_CODES: { code: string; label: string }[] = [
 [
  { "code": "+93", "label": "Afganistan" },
  { "code": "+49", "label": "Almanya" },
  { "code": "+1", "label": "Amerika Birleşik Devletleri" },
  { "code": "+1-684", "label": "Amerikan Samoası" },
  { "code": "+376", "label": "Andorra" },
  { "code": "+244", "label": "Angola" },
  { "code": "+1-264", "label": "Anguilla" },
  { "code": "+1-268", "label": "Antigua ve Barbuda" },
  { "code": "+54", "label": "Arjantin" },
  { "code": "+355", "label": "Arnavutluk" },
  { "code": "+297", "label": "Aruba" },
  { "code": "+61", "label": "Avustralya" },
  { "code": "+43", "label": "Avusturya" },
  { "code": "+994", "label": "Azerbaycan" },
  { "code": "+1-242", "label": "Bahamalar" },
  { "code": "+973", "label": "Bahreyn" },
  { "code": "+880", "label": "Bangladeş" },
  { "code": "+1-246", "label": "Barbados" },
  { "code": "+32", "label": "Belçika" },
  { "code": "+501", "label": "Belize" },
  { "code": "+229", "label": "Benin" },
  { "code": "+1-441", "label": "Bermuda" },
  { "code": "+375", "label": "Beyaz Rusya" },
  { "code": "+971", "label": "Birleşik Arap Emirlikleri" },
  { "code": "+44", "label": "Birleşik Krallık" },
  { "code": "+591", "label": "Bolivya" },
  { "code": "+387", "label": "Bosna Hersek" },
  { "code": "+267", "label": "Botsvana" },
  { "code": "+55", "label": "Brezilya" },
  { "code": "+673", "label": "Brunei" },
  { "code": "+359", "label": "Bulgaristan" },
  { "code": "+226", "label": "Burkina Faso" },
  { "code": "+257", "label": "Burundi" },
  { "code": "+975", "label": "Butan" },
  { "code": "+1-345", "label": "Cayman Adaları" },
  { "code": "+350", "label": "Cebelitarık" },
  { "code": "+213", "label": "Cezayir" },
  { "code": "+61", "label": "Christmas Adası" },
  { "code": "+253", "label": "Cibuti" },
  { "code": "+61", "label": "Cocos Adaları" },
  { "code": "+682", "label": "Cook Adaları" },
  { "code": "+235", "label": "Çad" },
  { "code": "+420", "label": "Çek Cumhuriyeti" },
  { "code": "+86", "label": "Çin" },
  { "code": "+45", "label": "Danimarka" },
  { "code": "+1-767", "label": "Dominika" },
  { "code": "+1-809", "label": "Dominik Cumhuriyeti" },
  { "code": "+593", "label": "Ekvador" },
  { "code": "+240", "label": "Ekvator Ginesi" },
  { "code": "+503", "label": "El Salvador" },
  { "code": "+62", "label": "Endonezya" },
  { "code": "+291", "label": "Eritre" },
  { "code": "+374", "label": "Ermenistan" },
  { "code": "+372", "label": "Estonya" },
  { "code": "+268", "label": "Esvatini" },
  { "code": "+251", "label": "Etiyopya" },
  { "code": "+500", "label": "Falkland Adaları" },
  { "code": "+298", "label": "Faroe Adaları" },
  { "code": "+212", "label": "Fas" },
  { "code": "+679", "label": "Fiji" },
  { "code": "+225", "label": "Fildişi Sahili" },
  { "code": "+63", "label": "Filipinler" },
  { "code": "+970", "label": "Filistin" },
  { "code": "+358", "label": "Finlandiya" },
  { "code": "+33", "label": "Fransa" },
  { "code": "+594", "label": "Fransız Guyanası" },
  { "code": "+689", "label": "Fransız Polinezyası" },
  { "code": "+241", "label": "Gabon" },
  { "code": "+220", "label": "Gambiya" },
  { "code": "+233", "label": "Gana" },
  { "code": "+224", "label": "Gine" },
  { "code": "+245", "label": "Gine-Bissau" },
  { "code": "+1-473", "label": "Grenada" },
  { "code": "+299", "label": "Grönland" },
  { "code": "+590", "label": "Guadeloupe" },
  { "code": "+1-671", "label": "Guam" },
  { "code": "+502", "label": "Guatemala" },
  { "code": "+27", "label": "Güney Afrika" },
  { "code": "+82", "label": "Güney Kore" },
  { "code": "+995", "label": "Gürcistan" },
  { "code": "+592", "label": "Guyana" },
  { "code": "+509", "label": "Haiti" },
  { "code": "+385", "label": "Hırvatistan" },
  { "code": "+91", "label": "Hindistan" },
  { "code": "+31", "label": "Hollanda" },
  { "code": "+504", "label": "Honduras" },
  { "code": "+852", "label": "Hong Kong" },
  { "code": "+964", "label": "Irak" },
  { "code": "+98", "label": "İran" },
  { "code": "+353", "label": "İrlanda" },
  { "code": "+34", "label": "İspanya" },
  { "code": "+972", "label": "İsrail" },
  { "code": "+46", "label": "İsveç" },
  { "code": "+41", "label": "İsviçre" },
  { "code": "+39", "label": "İtalya" },
  { "code": "+354", "label": "İzlanda" },
  { "code": "+1-876", "label": "Jamaika" },
  { "code": "+81", "label": "Japonya" },
  { "code": "+855", "label": "Kamboçya" },
  { "code": "+237", "label": "Kamerun" },
  { "code": "+1", "label": "Kanada" },
  { "code": "+382", "label": "Karadağ" },
  { "code": "+974", "label": "Katar" },
  { "code": "+7", "label": "Kazakistan" },
  { "code": "+254", "label": "Kenya" },
  { "code": "+357", "label": "Kıbrıs" },
  { "code": "+996", "label": "Kırgızistan" },
  { "code": "+686", "label": "Kiribati" },
  { "code": "+57", "label": "Kolombiya" },
  { "code": "+269", "label": "Komorlar" },
  { "code": "+242", "label": "Kongo" },
  { "code": "+506", "label": "Kosta Rika" },
  { "code": "+965", "label": "Kuveyt" },
  { "code": "+850", "label": "Kuzey Kore" },
  { "code": "+53", "label": "Küba" },
  { "code": "+856", "label": "Laos" },
  { "code": "+266", "label": "Lesotho" },
  { "code": "+371", "label": "Letonya" },
  { "code": "+231", "label": "Liberya" },
  { "code": "+218", "label": "Libya" },
  { "code": "+423", "label": "Liechtenstein" },
  { "code": "+370", "label": "Litvanya" },
  { "code": "+961", "label": "Lübnan" },
  { "code": "+352", "label": "Lüksemburg" },
  { "code": "+36", "label": "Macaristan" },
  { "code": "+261", "label": "Madagaskar" },
  { "code": "+853", "label": "Makao" },
  { "code": "+389", "label": "Makedonya" },
  { "code": "+265", "label": "Malavi" },
  { "code": "+60", "label": "Malezya" },
  { "code": "+960", "label": "Maldivler" },
  { "code": "+223", "label": "Mali" },
  { "code": "+356", "label": "Malta" },
  { "code": "+692", "label": "Marshall Adaları" },
  { "code": "+596", "label": "Martinik" },
  { "code": "+262", "label": "Mayotte" },
  { "code": "+52", "label": "Meksika" },
  { "code": "+20", "label": "Mısır" },
  { "code": "+691", "label": "Mikronezya" },
  { "code": "+373", "label": "Moldova" },
  { "code": "+377", "label": "Monako" },
  { "code": "+976", "label": "Moğolistan" },
  { "code": "+1-664", "label": "Montserrat" },
  { "code": "+222", "label": "Moritanya" },
  { "code": "+230", "label": "Mauritius" },
  { "code": "+258", "label": "Mozambik" },
  { "code": "+95", "label": "Myanmar" },
  { "code": "+264", "label": "Namibya" },
  { "code": "+674", "label": "Nauru" },
  { "code": "+977", "label": "Nepal" },
  { "code": "+227", "label": "Nijer" },
  { "code": "+234", "label": "Nijerya" },
  { "code": "+505", "label": "Nikaragua" },
  { "code": "+683", "label": "Niue" },
  { "code": "+47", "label": "Norveç" },
  { "code": "+236", "label": "Orta Afrika Cumhuriyeti" },
  { "code": "+998", "label": "Özbekistan" },
  { "code": "+92", "label": "Pakistan" },
  { "code": "+680", "label": "Palau" },
  { "code": "+507", "label": "Panama" },
  { "code": "+675", "label": "Papua Yeni Gine" },
  { "code": "+595", "label": "Paraguay" },
  { "code": "+51", "label": "Peru" },
  { "code": "+48", "label": "Polonya" },
  { "code": "+351", "label": "Portekiz" },
  { "code": "+1-787", "label": "Porto Riko" },
  { "code": "+262", "label": "Reunion" },
  { "code": "+40", "label": "Romanya" },
  { "code": "+250", "label": "Ruanda" },
  { "code": "+7", "label": "Rusya" },
  { "code": "+1-869", "label": "Saint Kitts ve Nevis" },
  { "code": "+1-758", "label": "Saint Lucia" },
  { "code": "+685", "label": "Samoa" },
  { "code": "+378", "label": "San Marino" },
  { "code": "+221", "label": "Senegal" },
  { "code": "+248", "label": "Seyşeller" },
  { "code": "+381", "label": "Sırbistan" },
  { "code": "+232", "label": "Sierra Leone" },
  { "code": "+65", "label": "Singapur" },
  { "code": "+421", "label": "Slovakya" },
  { "code": "+386", "label": "Slovenya" },
  { "code": "+677", "label": "Solomon Adaları" },
  { "code": "+252", "label": "Somali" },
  { "code": "+94", "label": "Sri Lanka" },
  { "code": "+249", "label": "Sudan" },
  { "code": "+597", "label": "Surinam" },
  { "code": "+963", "label": "Suriye" },
  { "code": "+966", "label": "Suudi Arabistan" },
  { "code": "+56", "label": "Şili" },
  { "code": "+992", "label": "Tacikistan" },
  { "code": "+255", "label": "Tanzanya" },
  { "code": "+66", "label": "Tayland" },
  { "code": "+886", "label": "Tayvan" },
  { "code": "+228", "label": "Togo" },
  { "code": "+676", "label": "Tonga" },
  { "code": "+1-868", "label": "Trinidad ve Tobago" },
  { "code": "+216", "label": "Tunus" },
  { "code": "+90", "label": "Türkiye" },
  { "code": "+993", "label": "Türkmenistan" },
  { "code": "+688", "label": "Tuvalu" },
  { "code": "+256", "label": "Uganda" },
  { "code": "+380", "label": "Ukrayna" },
  { "code": "+968", "label": "Umman" },
  { "code": "+598", "label": "Uruguay" },
  { "code": "+962", "label": "Ürdün" },
  { "code": "+678", "label": "Vanuatu" },
  { "code": "+39", "label": "Vatikan" },
  { "code": "+58", "label": "Venezuela" },
  { "code": "+84", "label": "Vietnam" },
  { "code": "+967", "label": "Yemen" },
  { "code": "+687", "label": "Yeni Kaledonya" },
  { "code": "+64", "label": "Yeni Zelanda" },
  { "code": "+238", "label": "Yeşil Burun Adaları" },
  { "code": "+30", "label": "Yunanistan" },
  { "code": "+260", "label": "Zambiya" },
  { "code": "+263", "label": "Zimbabve" }
]
]
